apiVersion: v1
kind: Service
metadata:
  name: kush-capstone-service
  namespace: kush-app-ns
  labels:
    app: kush-capstone-app
spec:
  type: LoadBalancer
  selector:
    app: kush-capstone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
