apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kush-capstone-cluster

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    volumeSize: 40
    ssh:
      allow: true