# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build_app:
    docker:
      - image: cimg/python:3.10.12
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            ls -la
            whoami
            pwd
            make setup
            source ~/.capstone/bin/activate
            make install
      - save_cache:
          paths:
            - ~/.capstone
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint!
      - run:
          name: run lint
          command: |
            source ~/.capstone/bin/activate
            make lint   
      # Run test
      - run:
          name: run test
          command: |
            source ~/.capstone/bin/activate
            make test

  build_docker_image:
    docker:
      - image: cimg/python:3.10.12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: List Files
          command: |
            ls -la 
      # Build Docker Image
      - run:
          name: Build Docker Image
          command: |
            docker build -t kushcapstone:${CIRCLE_WORKFLOW_ID:0:7} .
      # List Built Docker Image
      - run:
          name: Build Docker Image
          command: |
            docker image ls

workflows:
  default:
    jobs:
      - build_app
      - build_docker_image:
          requires:
            - build_app
