---
- name: Deploy ECR image to an EKS Cluster
  hosts: localhost
  gather_facts: false
  become: yes

  tasks:
    - name: Fetch AWS region from environment variable
      set_fact:
        aws_region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
      when: lookup('env', 'AWS_DEFAULT_REGION') is defined

    - name: Install eksctl
      shell: |
        curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz"
        tar -xzf "eksctl_Linux_amd64.tar.gz" -C /tmp 
        rm "eksctl_Linux_amd64.tar.gz"
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    
    - name: Check eksctl version
      shell: |
        eksctl version

    - name: Check kubectl version
      shell: |
        kubectl version --client=true

    - name: Check if cluster already exists
      shell: |
        eksctl get cluster -n kush-capstone-cluster --region {{ aws_region }}
      register: cluster_info
      ignore_errors: yes
      changed_when: false

    - name: Create EKS cluster if it does not exist
      shell: |
        eksctl create cluster ---name kush-capstone-cluster --region {{ aws_region }}
      when: cluster_info.rc != 0

    - name: Configure kubectl to EKS cluster
      shell: |
        aws eks update-kubeconfig --region {{ aws_region }} --name kush-capstone-cluster

    - name: Check Kubectl configuration
      shell: |
        kubectl get svc