---
- name: Install EKSCTL and Create EKS Cluster
  hosts: localhost
  gather_facts: false
  become: yes

  tasks:
    - name: Install eksctl
      shell: |
        curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz"
        tar -xzf "eksctl_Linux_amd64.tar.gz" -C /tmp 
        rm "eksctl_Linux_amd64.tar.gz"
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    
    - name: Check eksctl version
      shell: |
        eksctl version

    - name: Check kubectl version
      shell: |
        kubectl version --client=true
