apiVersion: apps/v1
kind: Deployment
metadata:
  name: kush-capstone-deployment
  namespace: kush-app-ns
  labels:
    app: kush-capstone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kush-capstone-app
  template:
    metadata:
      labels:
        app: kush-capstone-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - name: kushcapstone-app
        image: 633011985446.dkr.ecr.us-east-2.amazonaws.com/kushcapstone:latest
        ports:
        - name: http
          containerPort: 9090
        imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux

